name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Get ID Token Using GitHub Actions
        id: get_token
        run: echo "ID_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SKY_0AE6BB700 }}
          action: "upload"
          app_location: "/" # Đường dẫn mã nguồn ứng dụng
          api_location: "" # Đường dẫn mã nguồn API - tùy chọn
          output_location: "" # Thư mục chứa nội dung đã xây dựng của ứng dụng - tùy chọn
          github_id_token: ${{ env.ID_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
